### ISSUE TITLE
I tried to train with your code,but it didn't work.The main progress seems to stay waiting for something to load.

### ISSUE THREAD

**Issue by xiaoxiaoxiaogu** [advimman/CIPS#14]
/home/hello/miniconda3/envs/deepsort/bin/python3 /home/hello/桌面/CIPS-main/train.py LMDB_data1024*1024_anime --nproc_per_node=8 --master_port=1234 --n_sample=8 --batch=4 --fid_batch=8 --Generator=CIPSskip --output_dir=skip-[ffhq/churches] --img2dis --num_workers=16
Traceback (most recent call last):
  File "/home/hello/桌面/CIPS-main/train.py", line 16, in <module>
    import model
  File "/home/hello/桌面/CIPS-main/model/__init__.py", line 1, in <module>
    from .Discriminators import *
  File "/home/hello/桌面/CIPS-main/model/Discriminators.py", line 8, in <module>
    from .blocks import ConvLayer, ResBlock, EqualLinear
  File "/home/hello/桌面/CIPS-main/model/blocks.py", line 8, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/hello/桌面/CIPS-main/op/__init__.py", line 2, in <module>
    from .upfirdn2d import upfirdn2d
  File "/home/hello/桌面/CIPS-main/op/upfirdn2d.py", line 13, in <module>
    os.path.join(module_path, 'upfirdn2d_kernel.cu'),
  File "/home/hello/miniconda3/envs/deepsort/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1092, in load
    keep_intermediates=keep_intermediates)
  File "/home/hello/miniconda3/envs/deepsort/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1307, in _jit_compile
    baton.wait()
  File "/home/hello/miniconda3/envs/deepsort/lib/python3.7/site-packages/torch/utils/file_baton.py", line 42, in wait
    time.sleep(self.wait_seconds)
KeyboardInterrupt

Process finished with exit code 1

**Comment by jaepoong** [comment]
i struggling same error

**Comment by 123456klk1** [comment]
i struggling same error

**Comment by vox-1** [comment]
hello ,I meet the same issue. Have you solved  it?

**Comment by martober** [comment]
If anyone sees this, the issue is that it is trying to build cpp code but gets stuck for whatever reason. The solution I found is to find the cache folder for the build and delete it, which fixed the problem for me. You can do this by placing print(build_directory) before baton.wait() in the "cpp_extension.py" file that appears in the error logs.
